version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: turianpy/api_foodgram:latest
    restart: always
    volumes:
      - static_backend_value:/app/static_backend/
      - media_value:/app/media/
      - ../backend:/app
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: turianpy/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_backend_value:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  static_backend_value:
  media_value:
  db:
  result_build:
