# Generated by Django 4.2 on 2023-04-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, related_name='added_to_cart_by', to='recipes.recipe'),
        ),
    ]
